/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.embiimob.supmobile;

public final class R {
  public static final class id {
    public static final int btnMint=0x7f010000;
    public static final int btnRefresh=0x7f010001;
    public static final int btnSelectFolder=0x7f010002;
    public static final int feedOutput=0x7f010003;
    public static final int inputMsg=0x7f010004;
    public static final int statusIndicator=0x7f010005;
    public static final int toggleLocalMode=0x7f010006;
  }
  public static final class layout {
    public static final int activity_main=0x7f020000;
  }
}